LCD-49511 Update `curl` structure to be aligned with existing pattern

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -48,19 +48,24 @@ liferay-default:
                                     local url="https://releases.liferay.com/opensearch2/dxp/${product_version}/${filename_prefix}.{api,impl}.jar"
 
                                     rm --recursive --verbose /temp/osgi/modules/*opensearch*
+
                                     mkdir -p "$deploy_dir"
 
-                                    if ! curl \
-                                        --fail \
-                                        --location \
-                                        --output-dir "$deploy_dir" \
-                                        --remote-name \
-                                        --retry 5 \
-                                        --retry-all-errors \
-                                        --retry-delay 2 \
-                                        "$url" ; then
-                                            echo "Unable to download OpenSearch modules for Product Version ${PRODUCT_VERSION}." >&2
-                                            exit 1
+                                    local http_code=$(\
+                                      curl \
+                                          "$url"
+                                          --fail \
+                                          --location \
+                                          --output-dir "$deploy_dir" \
+                                          --remote-name \
+                                          --retry 5 \
+                                          --retry-all-errors \
+                                          --retry-delay 2 \
+                                          --write-out "%{http_code}")
+
+                                    if [ "${http_code}" != "200" ] ; then
+                                        echo "Unable to download OpenSearch modules for Product Version ${PRODUCT_VERSION}." >&2
+                                        exit 1
                                     fi
                                 }
 
