LCD-49468 Base-line for how initContainer will be implemented on AWS

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -79,3 +79,55 @@ liferay-default:
                     requests:
                         storage: 10Gi
                 storageClassName: gp3
+    customInitContainers:
+        x-install-opensearch-module:
+            - containerTemplate: |
+                  -   command:
+                          -   bash
+                          -   -c
+                          -   |
+                                #!/usr/bin/env bash
+
+                                set -e
+
+                                PRODUCT_VERSION=2025.q1.17-lts
+                                DOWNLOAD_FOLDER="$(mktemp -d)"
+
+                                VALIDATE_IF_OPENSEARCH_IS_ALREADY_INSTALLED() {
+                                  if [[ -f "opensearch" ]] ; then
+                                    exit 0
+                                  fi
+                                }
+
+                                DOWNLOAD_OPENSEARCH_MODULES() {
+                                  local URL="https://releases.liferay.com/opensearch2/dxp/${PRODUCT_VERSION}"
+
+                                  if curl -sL -f \
+                                    --output-dir "${DOWNLOAD_FOLDER}" \
+                                    -O \
+                                    --retry 5 \
+                                    --retry-delay 2 \
+                                    --retry-all-errors \
+                                    "$URL"; then
+                                      echo "Success: Product version ${PRODUCT_VERSION} installed."
+                                  else
+                                    local EXIT_CODE=$?
+                                    echo "Error: Failed to download Opensearch modules (Exit code: ${EXIT_CODE})."
+                                    exit 1
+                                  fi
+                                }
+
+                                MAIN() {
+                                  VALIDATE_IF_OPENSEARCH_IS_ALREADY_INSTALLED "$PRODUCT_VERSION"
+                                  DOWNLOAD_OPENSEARCH_MODULES "$PRODUCT_VERSION"
+
+                                  mv "${DOWNLOAD_FOLDER}"/* "/mnt/deploy"
+                                }
+
+                                MAIN "$PRODUCT_VERSION"
+                      image: curlimages/curl:latest
+                      name: liferay-install-opensearch-module
+                      volumeMounts:
+                          -   mountPath: /mnt/deploy
+                              name: liferay-persistent-volume
+                              subPath: /opt/liferay/deploy
