LCD-49511 SF

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -34,45 +34,50 @@ liferay-default:
                   name: managed-service-details
     customInitContainers:
         x-liferay-install-opensearch-modules:
-            - containerTemplate: |
-                  - command:
-                        - sh
-                        - -c
-                        - |
-                              set -e
-                              echo "Cleaning-up old OpenSearch modules to prevent conflicts..."
-                              rm \
-                                  -r \
-                                  -f \
-                                  -v /temp/osgi/modules/*opensearch*
-                              DEPLOY_DIR=/temp/liferay/deploy
-                              PRODUCT_VERSION={{.image.tag}}
-                              mkdir -p "$DEPLOY_DIR"
-                              function main {
-                                  local FILE_NAME_PREFIX="com.liferay.portal.search.opensearch2"
-                                  local URL="https://releases.liferay.com/opensearch2/dxp/${PRODUCT_VERSION}/${FILE_NAME_PREFIX}.{api,impl}.jar"
-                                  if ! curl \
-                                      --fail \
-                                      --location \
-                                      --output-dir "$DEPLOY_DIR" \
-                                      --remote-name \
-                                      --retry 5 \
-                                      --retry-all-errors \
-                                      --retry-delay 2 \
-                                      "$URL" ; then
-                                          echo "Error: Failed to install OpenSearch modules." >&2
-                                          echo "If your current image already has OpenSearch installed, you may disable this validation by setting \".search.setup=false\" onto your Helm chart." >&2
-                                          exit 1
-                                  fi
-                              }
-                              echo "Starting to install OpenSearch modules for Product Version ${PRODUCT_VERSION}..."
-                              main "$PRODUCT_VERSION"
-                              echo "OpenSearch modules installed successfully."
-                    image: curlimages/curl:latest
-                    name: liferay-install-opensearch-modules
-                    volumeMounts:
-                        - mountPath: /temp
-                          name: liferay-persistent-volume
+            -   containerTemplate: |
+                    - command:
+                          - sh
+                          - -c
+                          - |
+                                set -e
+                                echo "Cleaning-up old OpenSearch modules to prevent conflicts..."
+                                rm \
+                                    -r \
+                                    -f \
+                                    -v /temp/osgi/modules/*opensearch*
+
+                                DEPLOY_DIR=/temp/liferay/deploy
+                                PRODUCT_VERSION={{.image.tag}}
+
+                                mkdir -p "$DEPLOY_DIR"
+
+                                function main {
+                                    local FILE_NAME_PREFIX="com.liferay.portal.search.opensearch2"
+                                    local URL="https://releases.liferay.com/opensearch2/dxp/${PRODUCT_VERSION}/${FILE_NAME_PREFIX}.{api,impl}.jar"
+
+                                    if ! curl \
+                                        --fail \
+                                        --location \
+                                        --output-dir "$DEPLOY_DIR" \
+                                        --remote-name \
+                                        --retry 5 \
+                                        --retry-all-errors \
+                                        --retry-delay 2 \
+                                        "$URL" ; then
+                                            echo "Error: Failed to install OpenSearch modules." >&2
+                                            echo "If your current image already has OpenSearch installed, you may disable this validation by setting \".search.setup=false\" onto your Helm chart." >&2
+                                            exit 1
+                                    fi
+                                }
+
+                                echo "Starting to install OpenSearch modules for Product Version ${PRODUCT_VERSION}..."
+                                main "$PRODUCT_VERSION"
+                                echo "OpenSearch modules installed successfully."
+                      image: curlimages/curl:latest
+                      name: liferay-install-opensearch-modules
+                      volumeMounts:
+                          - mountPath: /temp
+                            name: liferay-persistent-volume
         x-liferay-overlay:
             - containerTemplate: |
                   - command:
